import React, { useEffect, useMemo, useRef, useState } from 'react';
import ReactDOM from 'react-dom/client';
import { createClient, type Session } from '@supabase/supabase-js';
import { BarChart3, CalendarDays, Check, Home, List, Loader2, LogOut, PiggyBank, Plus, RefreshCw, TrendingUp, Wifi, WifiOff, X } from 'lucide-react';
import './styles.css';

type Kind='expense'|'income';
type Category={id:string;user_id:string;type:Kind;name:string;icon:string;is_default:boolean;created_at:string;updated_at:string;pending?:boolean};
type Account={id:string;user_id:string;name:string;icon:string|null;opening_balance:number;created_at:string;updated_at:string;pending?:boolean};
type Operation={id:string;user_id:string;type:Kind;amount:number;category_id:string|null;category_name:string;account_id:string|null;account_name:string;date:string;comment:string|null;created_at:string;updated_at:string;deleted_at:string|null;pending?:boolean};
type Goal={id:string;user_id:string;name:string;target:number;current:number;created_at:string;updated_at:string;deleted_at:string|null;pending?:boolean};
type AppData={operations:Operation[];categories:Category[];accounts:Account[];goals:Goal[];currency:string};
type QueueItem={id:string;table:'operations'|'categories'|'accounts'|'goals';action:'insert'|'update'|'delete';payload:any};

const url=import.meta.env.VITE_SUPABASE_URL as string|undefined;
const anon=import.meta.env.VITE_SUPABASE_ANON_KEY as string|undefined;
const supabase=url&&anon?createClient(url,anon):null;
const empty:AppData={operations:[],categories:[],accounts:[],goals:[],currency:'₽'};
const icons:Record<string,string>={food:'🥦',transport:'🚕',restaurant:'🍽️',smoking:'🚬',health:'💊',sport:'🏃',clothes:'👕',subscriptions:'⏱',entertainment:'🎬',home:'🏠',rent:'🏢','rent-payment':'🧾',credit:'💳',business:'💼',debt:'🤝',other:'…',gift:'🎁',card:'💳',cash:'💵',crypto:'₿'};
const iconIds=Object.keys(icons);
const expenseDefaults=[['продукты','food'],['транспорт','transport'],['еда вне дома','restaurant'],['курение','smoking'],['здоровье','health'],['спорт','sport'],['одежда','clothes'],['подписки','subscriptions'],['развлечения','entertainment'],['дом','home'],['аренда квартиры','rent'],['оплаты за сдачу жилья','rent-payment'],['кредиты','credit'],['бизнес','business'],['долг','debt'],['другое','other']];
const incomeDefaults=[['зп nonteam','business'],['фриланс','business'],['сдача жилья','rent'],['подарки','gift'],['прочее','other']];
const accountDefaults=[['карта','card'],['наличка','cash'],['крипта','crypto'],['другое','other']];
const colors=['#3b5bff','#22c7a9','#f59e0b','#ef476f','#8b5cf6','#14b8a6','#94a3b8','#60a5fa'];
const uid=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
const money=(n:number,c='₽')=>`${new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Math.round(n||0))} ${c}`;
const amount=(v:string)=>Number(v.replace(',','.').replace(/\s/g,''))||0;
const haptic=(ms=10)=>navigator.vibrate?.(ms);
const dataKey=(u:string)=>`money:data:${u}`;
const queueKey=(u:string)=>`money:queue:${u}`;
const loadCache=(u:string)=>{try{return JSON.parse(localStorage.getItem(dataKey(u))||'null') as AppData|null}catch{return null}};
const saveCache=(u:string,d:AppData)=>localStorage.setItem(dataKey(u),JSON.stringify(d));
const loadQueue=(u:string)=>{try{return JSON.parse(localStorage.getItem(queueKey(u))||'[]') as QueueItem[]}catch{return[]}};
const saveQueue=(u:string,q:QueueItem[])=>localStorage.setItem(queueKey(u),JSON.stringify(q));
const makeCategories=(u:string)=>{const t=now();return [...expenseDefaults.map(([name,icon])=>({id:uid(),user_id:u,type:'expense' as Kind,name,icon,is_default:true,created_at:t,updated_at:t})),...incomeDefaults.map(([name,icon])=>({id:uid(),user_id:u,type:'income' as Kind,name,icon,is_default:true,created_at:t,updated_at:t}))]};
const makeAccounts=(u:string)=>{const t=now();return accountDefaults.map(([name,icon])=>({id:uid(),user_id:u,name,icon,opening_balance:0,created_at:t,updated_at:t}))};

async function applyMutation(m:QueueItem){if(!supabase)throw new Error('Supabase не настроен');const clean={...m.payload};delete clean.pending;if(m.action==='insert'){const{error}=await supabase.from(m.table).insert(clean);if(error)throw error;return}if(m.action==='update'){const{error}=await supabase.from(m.table).update({...clean,updated_at:now()}).eq('id',clean.id);if(error)throw error;return}if(m.table==='operations'||m.table==='goals'){const{error}=await supabase.from(m.table).update({deleted_at:now(),updated_at:now()}).eq('id',clean.id);if(error)throw error;return}const{error}=await supabase.from(m.table).delete().eq('id',clean.id);if(error)throw error;}
async function flushQueue(u:string){const q=loadQueue(u);const failed:QueueItem[]=[];let sent=0;for(const m of q){try{await applyMutation(m);sent++}catch{failed.push(m)}}saveQueue(u,failed);return sent;}
async function enqueue(u:string,m:Omit<QueueItem,'id'>){saveQueue(u,[...loadQueue(u),{...m,id:uid()}]);if(navigator.onLine)await flushQueue(u);}
async function bootstrapUser(u:string,email?:string){if(!supabase)return;const stamp=now();const{data:profile}=await supabase.from('profiles').select('id').eq('user_id',u).maybeSingle();if(!profile)await supabase.from('profiles').insert({id:uid(),user_id:u,display_name:email?.split('@')[0]??null,currency:'₽',created_at:stamp,updated_at:stamp});const[{count:cc},{count:ac}]=await Promise.all([supabase.from('categories').select('id',{count:'exact',head:true}).eq('user_id',u),supabase.from('accounts').select('id',{count:'exact',head:true}).eq('user_id',u)]);if(!cc)await supabase.from('categories').insert(makeCategories(u));if(!ac)await supabase.from('accounts').insert(makeAccounts(u));}
async function fetchData(u:string):Promise<AppData>{if(!supabase)throw new Error('Supabase не настроен');await flushQueue(u);const[p,o,c,a,g]=await Promise.all([supabase.from('profiles').select('currency').eq('user_id',u).maybeSingle(),supabase.from('operations').select('*').eq('user_id',u).is('deleted_at',null).order('date',{ascending:false}),supabase.from('categories').select('*').eq('user_id',u).order('created_at',{ascending:true}),supabase.from('accounts').select('*').eq('user_id',u).order('created_at',{ascending:true}),supabase.from('goals').select('*').eq('user_id',u).is('deleted_at',null).order('created_at',{ascending:false})]);const err=[p.error,o.error,c.error,a.error,g.error].find(Boolean);if(err)throw err;return{currency:p.data?.currency??'₽',operations:o.data??[],categories:c.data?.length?c.data:makeCategories(u),accounts:a.data?.length?a.data:makeAccounts(u),goals:g.data??[]};}

function App(){const[session,setSession]=useState<Session|null>(null);const[data,setData]=useState<AppData>(empty);const[screen,setScreen]=useState('home');const[loading,setLoading]=useState(true);const[syncing,setSyncing]=useState(false);const[online,setOnline]=useState(navigator.onLine);const[toast,setToast]=useState('');const user=session?.user;const show=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2200)};const persist=(d:AppData)=>{setData(d);if(user)saveCache(user.id,d)};const refresh=async()=>{if(!user||!supabase)return;setSyncing(true);try{await bootstrapUser(user.id,user.email);const remote=await fetchData(user.id);persist(remote);show('синхронизировано')}catch(e){show(e instanceof Error?e.message:'ошибка синхронизации')}finally{setLoading(false);setSyncing(false)}};
useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
useEffect(()=>{if(!user)return;const cached=loadCache(user.id);if(cached)setData(cached);refresh()},[user?.id]);
useEffect(()=>{const on=()=>{setOnline(true);if(user)flushQueue(user.id).then(n=>{if(n)show(`очередь отправлена: ${n}`);refresh()})};const off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[user?.id]);
const mutate=async(next:AppData,m:Omit<QueueItem,'id'>,ok:string)=>{if(!user)return;const prev=data;persist(next);haptic();try{await enqueue(user.id,m);show(ok)}catch(e){persist(prev);show(e instanceof Error?e.message:'не удалось сохранить')}};
const addOperation=(op:Operation)=>mutate({...data,operations:[op,...data.operations]},{table:'operations',action:'insert',payload:op},op.type==='expense'?'трата сохранена':'доход сохранен');
const addCategory=(cat:Category)=>mutate({...data,categories:[...data.categories,cat]},{table:'categories',action:'insert',payload:cat},'категория добавлена');
const addGoal=(goal:Goal)=>mutate({...data,goals:[goal,...data.goals]},{table:'goals',action:'insert',payload:goal},'цель создана');
const updateGoal=(goal:Goal)=>mutate({...data,goals:data.goals.map(g=>g.id===goal.id?goal:g)},{table:'goals',action:'update',payload:goal},'цель обновлена');
const deleteGoal=(goal:Goal)=>mutate({...data,goals:data.goals.filter(g=>g.id!==goal.id)},{table:'goals',action:'delete',payload:goal},'цель удалена');
if(!user)return <><Auth/><Toast msg={toast}/></>;const ops=data.operations.filter(o=>!o.deleted_at);const income=ops.filter(o=>o.type==='income').reduce((s,o)=>s+Number(o.amount),0);const expense=ops.filter(o=>o.type==='expense').reduce((s,o)=>s+Number(o.amount),0);const opening=data.accounts.reduce((s,a)=>s+Number(a.opening_balance),0);const balance=opening+income-expense;const spentToday=ops.filter(o=>o.type==='expense'&&o.date===today()).reduce((s,o)=>s+Number(o.amount),0);const nav=[['home','траты',Home],['income','доходы',TrendingUp],['analytics','аналитика',BarChart3],['goals','цели',PiggyBank],['history','история',List]] as const;
return <div className="app"><header className="top"><div><span>Сколько стоят деньги</span><h1>{({home:'Расходы',income:'Доходы',analytics:'Аналитика',goals:'Фин. цели',history:'История'} as any)[screen]}</h1></div><div className="top-actions"><b className={online?'online':'offline'}>{online?<Wifi size={15}/>:<WifiOff size={15}/>} {loadQueue(user.id).length|| (online?'online':'offline')}</b><button className="icon" onClick={refresh}><RefreshCw className={syncing?'spin':''}/></button><button className="icon desktop" onClick={()=>supabase?.auth.signOut()}><LogOut/></button></div></header><nav className="desktop-nav">{nav.map(([id,label,Icon])=><button key={id} className={screen===id?'active':''} onClick={()=>setScreen(id)}><Icon size={18}/>{label}</button>)}</nav>{loading?<Skeleton/>:<main>{screen==='home'&&<HomeScreen user={user.id} data={data} balance={balance} spentToday={spentToday} ops={ops} addOperation={addOperation} addCategory={addCategory}/>} {screen==='income'&&<Flow type="income" user={user.id} data={data} addOperation={addOperation} addCategory={addCategory}/>} {screen==='analytics'&&<Analytics data={data} ops={ops}/>} {screen==='goals'&&<Goals user={user.id} data={data} addGoal={addGoal} updateGoal={updateGoal} deleteGoal={deleteGoal}/>} {screen==='history'&&<History data={data} ops={ops}/>}</main>}<nav className="tabs">{nav.map(([id,label,Icon])=><button key={id} className={screen===id?'active':''} onClick={()=>setScreen(id)}><Icon size={20}/><span>{label}</span></button>)}</nav><Toast msg={toast}/></div>}

function Auth(){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[magic,setMagic]=useState(false);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const submit=async()=>{if(!supabase||!email)return;setBusy(true);const res=magic?await supabase.auth.signInWithOtp({email}):await supabase.auth.signInWithPassword({email,password});if(res.error&&!magic){const sign=await supabase.auth.signUp({email,password});setMsg(sign.error?.message||'письмо подтверждения отправлено')}else setMsg(res.error?.message||(magic?'magic link отправлен':'готово'));setBusy(false)};return <main className="auth"><section><h1>Сколько стоят деньги</h1><p>Войдите, чтобы увидеть свои финансовые данные.</p>{!supabase&&<div className="notice">Добавьте VITE_SUPABASE_URL и VITE_SUPABASE_ANON_KEY.</div>}<div className="seg"><button className={!magic?'active':''} onClick={()=>setMagic(false)}>пароль</button><button className={magic?'active':''} onClick={()=>setMagic(true)}>magic link</button></div><input placeholder="email" value={email} onChange={e=>setEmail(e.target.value)}/>{!magic&&<input type="password" placeholder="пароль" value={password} onChange={e=>setPassword(e.target.value)}/>}<button className="primary" disabled={!supabase||busy||!email} onClick={submit}>{busy?<Loader2 className="spin"/>:'войти'}</button>{msg&&<p>{msg}</p>}</section></main>}
function HomeScreen(p:{user:string;data:AppData;balance:number;spentToday:number;ops:Operation[];addOperation:(o:Operation)=>void;addCategory:(c:Category)=>void}){const bal=(a:Account)=>p.ops.filter(o=>o.account_id===a.id).reduce((s,o)=>s+(o.type==='income'?o.amount:-o.amount),Number(a.opening_balance));return <div className="screen home"><section className="balance"><span>общий баланс</span><strong>{money(p.balance,p.data.currency)}</strong><small>сегодня потрачено: {money(p.spentToday,p.data.currency)}</small></section><section className="accounts">{p.data.accounts.map(a=><article key={a.id}><span>{icons[a.icon||'other']}</span><b>{a.name}</b><strong>{money(bal(a),p.data.currency)}</strong></article>)}</section><Flow type="expense" user={p.user} data={p.data} addOperation={p.addOperation} addCategory={p.addCategory}/></div>}
function Flow({type,user,data,addOperation,addCategory}:{type:Kind;user:string;data:AppData;addOperation:(o:Operation)=>void;addCategory:(c:Category)=>void}){const[step,setStep]=useState(1);const[sum,setSum]=useState('');const[cat,setCat]=useState('');const[acc,setAcc]=useState('');const[date,setDate]=useState(today());const[comment,setComment]=useState('');const[modal,setModal]=useState(false);const cats=data.categories.filter(c=>c.type===type);const c=cats.find(x=>x.id===cat)||cats[0];const a=data.accounts.find(x=>x.id===acc)||data.accounts[0];const save=()=>{const n=amount(sum);if(!n||!c||!a)return;const t=now();addOperation({id:uid(),user_id:user,type,amount:n,category_id:c.id,category_name:c.name,account_id:a.id,account_name:a.name,date,comment:comment||null,created_at:t,updated_at:t,deleted_at:null,pending:true});setStep(1);setSum('');setComment('');};return <section className="card flow"><header><div><span>{type==='expense'?'новая трата':'новый доход'}</span><h2>{step===1?'Сумма':step===2?'Категория':'Детали'}</h2></div></header><div className="dots"><i className={step>=1?'on':''}/><i className={step>=2?'on':''}/><i className={step>=3?'on':''}/></div>{step===1&&<><input className="amount" inputMode="decimal" placeholder="0" value={sum} onChange={e=>setSum(e.target.value)}/><button className="primary" disabled={!amount(sum)} onClick={()=>setStep(2)}>дальше</button></>}{step===2&&<><div className="chips">{cats.map(x=><button className={x.id===c?.id?'active':''} key={x.id} onClick={()=>setCat(x.id)}>{icons[x.icon]||icons.other} {x.name}</button>)}<button onClick={()=>setModal(!modal)}><Plus size={17}/> добавить новую</button></div><button className="primary" onClick={()=>setStep(3)}>дальше</button></>}{step===3&&<><div className="accounts-select">{data.accounts.map(x=><button className={x.id===a?.id?'active':''} key={x.id} onClick={()=>setAcc(x.id)}>{icons[x.icon||'other']} <span>{x.name}</span></button>)}</div><div className="date-line"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="icon"><CalendarDays/></button></div><textarea placeholder="Комментарий" value={comment} onChange={e=>setComment(e.target.value)}/><button className="primary" onClick={save}><Check size={18}/> зафиксировать</button></>}{modal&&<CategoryModal type={type} user={user} close={()=>setModal(false)} save={cat=>{addCategory(cat);setCat(cat.id);setModal(false)}}/>}</section>}
function CategoryModal({type,user,close,save}:{type:Kind;user:string;close:()=>void;save:(c:Category)=>void}){const[name,setName]=useState('');const[icon,setIcon]=useState('other');return <div className="backdrop" onClick={close}><section className="modal" onClick={e=>e.stopPropagation()}><header><h2>Новая категория</h2><button className="icon" onClick={close}><X/></button></header><input placeholder="название" value={name} onChange={e=>setName(e.target.value)}/><div className="icon-grid">{iconIds.map(i=><button className={icon===i?'active':''} key={i} onClick={()=>setIcon(i)}>{icons[i]}</button>)}</div><button className="primary" onClick={()=>{const t=now();if(name.trim())save({id:uid(),user_id:user,type,name:name.trim(),icon,is_default:false,created_at:t,updated_at:t,pending:true})}}>сохранить</button></section></div>}
function Analytics({data,ops}:{data:AppData;ops:Operation[]}){const[month,setMonth]=useState(new Date().toISOString().slice(0,7));const[type,setType]=useState<Kind>('expense');const rows=useMemo(()=>{const m=new Map<string,{name:string;icon:string;amount:number}>();ops.filter(o=>o.date.startsWith(month)&&o.type===type).forEach(o=>{const cat=data.categories.find(c=>c.id===o.category_id);const key=o.category_id||o.category_name;const row=m.get(key)||{name:o.category_name,icon:cat?.icon||'other',amount:0};row.amount+=o.amount;m.set(key,row)});return[...m.values()].sort((a,b)=>b.amount-a.amount)},[ops,month,type]);const income=ops.filter(o=>o.date.startsWith(month)&&o.type==='income').reduce((s,o)=>s+o.amount,0);const expense=ops.filter(o=>o.date.startsWith(month)&&o.type==='expense').reduce((s,o)=>s+o.amount,0);const total=rows.reduce((s,r)=>s+r.amount,0);return <div className="screen"><section className="toolbar"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><div className="seg"><button className={type==='expense'?'active':''} onClick={()=>setType('expense')}>расходы</button><button className={type==='income'?'active':''} onClick={()=>setType('income')}>доходы</button></div></section><section className="summary"><div>Доходы<strong className="good">{money(income,data.currency)}</strong></div><div>Расходы<strong className="bad">{money(expense,data.currency)}</strong></div></section><section className="analytics"><Donut rows={rows}/><div className="listrows">{rows.length?rows.map((r,i)=><article key={r.name}><span>{icons[r.icon]}</span><div><strong>{r.name}</strong><small>{total?Math.round(r.amount/total*100):0}%</small></div><b>{money(r.amount,data.currency)}</b></article>):<Empty text="За месяц пока пусто"/>}</div></section></div>}
function Donut({rows}:{rows:{amount:number}[]}){const ref=useRef<HTMLCanvasElement|null>(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const rect=canvas.getBoundingClientRect();const dpr=devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);const total=rows.reduce((s,r)=>s+r.amount,0);const r=Math.min(rect.width,rect.height)/2-18;ctx.lineWidth=28;ctx.lineCap='round';let start=-Math.PI/2;if(!total){ctx.strokeStyle='#e5e9f2';ctx.beginPath();ctx.arc(rect.width/2,rect.height/2,r,0,Math.PI*2);ctx.stroke();return}rows.forEach((row,i)=>{const a=row.amount/total*Math.PI*2;ctx.strokeStyle=colors[i%colors.length];ctx.beginPath();ctx.arc(rect.width/2,rect.height/2,r,start,start+a-.03);ctx.stroke();start+=a})},[rows]);return <canvas className="donut" ref={ref}/>}
function Goals({user,data,addGoal,updateGoal,deleteGoal}:{user:string;data:AppData;addGoal:(g:Goal)=>void;updateGoal:(g:Goal)=>void;deleteGoal:(g:Goal)=>void}){const[name,setName]=useState('');const[target,setTarget]=useState('');const create=()=>{const n=amount(target);if(!name||!n)return;const t=now();addGoal({id:uid(),user_id:user,name,target:n,current:0,created_at:t,updated_at:t,deleted_at:null,pending:true});setName('');setTarget('')};return <div className="screen goals"><section className="card goal-create"><h2>Фин. цели</h2><input placeholder="Название" value={name} onChange={e=>setName(e.target.value)}/><input inputMode="decimal" placeholder="Сумма" value={target} onChange={e=>setTarget(e.target.value)}/><button className="primary" onClick={create}><Plus size={18}/> создать</button></section><section className="goal-list">{data.goals.length?data.goals.map(g=><GoalCard key={g.id} g={g} currency={data.currency} update={updateGoal} del={deleteGoal}/>):<Empty text="Целей пока нет"/>}</section></div>}
function GoalCard({g,currency,update,del}:{g:Goal;currency:string;update:(g:Goal)=>void;del:(g:Goal)=>void}){const[sum,setSum]=useState('');const[edit,setEdit]=useState(false);const pct=Math.min(100,Math.round(g.current/g.target*100));return <article className="card goal"><button className="more" onClick={()=>setEdit(!edit)}>⋯</button>{edit&&<div className="menu"><button onClick={()=>{const name=prompt('Название',g.name)||g.name;const target=amount(prompt('Цель',String(g.target))||String(g.target))||g.target;const current=amount(prompt('Сейчас',String(g.current))||String(g.current));update({...g,name,target,current,updated_at:now(),pending:true});setEdit(false)}}>редактировать</button><button className="bad" onClick={()=>confirm('Удалить цель?')&&del(g)}>удалить</button></div>}<h3>{g.name}</h3><p>{money(g.current,currency)} / {money(g.target,currency)}</p><strong>{pct}%</strong><div className="progress"><i style={{width:`${pct}%`}}/></div><div className="add"><input inputMode="decimal" placeholder="добавить сумму" value={sum} onChange={e=>setSum(e.target.value)}/><button className="primary" onClick={()=>{const n=amount(sum);if(n){update({...g,current:g.current+n,updated_at:now(),pending:true});setSum('')}}}>+ добавить</button></div></article>}
function History({data,ops}:{data:AppData;ops:Operation[]}){const[acc,setAcc]=useState('');const[cat,setCat]=useState('');const[all,setAll]=useState(false);const[date,setDate]=useState('');const sorted=[...ops].sort((a,b)=>b.date.localeCompare(a.date)||b.created_at.localeCompare(a.created_at));const last=sorted[0]?.date;const rows=sorted.filter(o=>(!acc||o.account_id===acc)&&(!cat||o.category_id===cat)&&(!date||o.date===date)&&(all||date||!last||o.date===last));const groups=rows.reduce((m,o)=>{(m[o.date]??=[]).push(o);return m},{} as Record<string,Operation[]>);return <div className="screen history"><section className="filters"><select value={acc} onChange={e=>setAcc(e.target.value)}><option value="">все счета</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select value={cat} onChange={e=>setCat(e.target.value)}><option value="">все категории</option>{data.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input aria-label="дата" type="date" value={date} onChange={e=>{setDate(e.target.value);setAll(true)}}/></section><section className="history-list">{rows.length?Object.entries(groups).map(([d,items])=><div className="day" key={d}><h3>{new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',weekday:'short'}).format(new Date(d))}</h3>{items.map(o=><article className="hrow" key={o.id}><span>{icons[data.categories.find(c=>c.id===o.category_id)?.icon||'other']}</span><div><strong>{o.category_name}</strong><small>{o.account_name}{o.comment?` · ${o.comment}`:''}</small></div><b className={o.type==='income'?'good':'bad'}>{o.type==='income'?'+':'-'}{money(o.amount,data.currency)}</b></article>)}</div>):<Empty text="История пуста"/>}</section>{!all&&sorted.length>rows.length&&<button className="secondary" onClick={()=>setAll(true)}>показать все</button>}</div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function Toast({msg}:{msg:string}){return msg?<div className="toast">{msg}</div>:null}
function Skeleton(){return <main><div className="skeleton tall"/><div className="skeleton"/></main>}

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
if('serviceWorker'in navigator&&import.meta.env.PROD)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
